In [1]:
import torch
from usta_model import UstaModel
from usta_tokenizer import UstaTokenizer

u_tokenizer = UstaTokenizer("tokenizer.json")

prompt = "the capital of united"

tokens = u_tokenizer.encode(prompt)
tokens

tensor([ 0, 61,  1, 61,  2, 61,  3])

In [2]:
torch.manual_seed(1)
u_model = UstaModel(vocab_size=len(u_tokenizer.vocab), embedding_dim=4,context_length=32)

sentence_meanings_with_attention_context = u_model(tokens)
sentence_meanings_with_attention_context.shape

torch.Size([7, 4])

In [3]:
out = u_model(tokens)
out

tensor([[ 0.9772, -1.3495, -0.5732,  0.9455],
        [-0.0395, -0.9131, -0.6877,  1.6403],
        [ 1.6857, -0.7827, -0.1970, -0.7059],
        [-0.8299, -0.0373, -0.7770,  1.6442],
        [-1.0705,  0.9870, -0.9242,  1.0077],
        [ 1.5739, -1.1250,  0.0519, -0.5008],
        [ 0.0441,  0.7411, -1.6437,  0.8585]], grad_fn=<MulBackward0>)

In [4]:
u_model

UstaModel(
  (embedding): Embedding(64, 4)
  (pos_embedding): Embedding(32, 4)
  (self_attention): UstaMultiHeadAttention(
    (multi_head_attention): MultiheadAttention(
      (out_proj): NonDynamicallyQuantizableLinear(in_features=4, out_features=4, bias=True)
    )
    (projection): Linear(in_features=4, out_features=4, bias=True)
  )
  (norm): UstaLayerNorm()
)

In [5]:
from usta_layer_norm import UstaLayerNorm

norm_layer = UstaLayerNorm(4)
norm_layer(out)

tensor([[ 0.9774, -1.3497, -0.5733,  0.9456],
        [-0.0395, -0.9133, -0.6878,  1.6405],
        [ 1.6875, -0.7836, -0.1973, -0.7067],
        [-0.8302, -0.0373, -0.7773,  1.6448],
        [-1.0719,  0.9883, -0.9254,  1.0090],
        [ 1.5746, -1.1255,  0.0519, -0.5010],
        [ 0.0441,  0.7421, -1.6458,  0.8596]], grad_fn=<MulBackward0>)